language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
  - '8'
before_install:
  - npm install -g npm
  - npm install -g greenkeeperio/greenkeeper-lockfile@2
install:
  - npm install
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/
